/* 关键模块：集中维护已经通过基础可访问性核验的第三方浏览器游戏。 */
/* 每条记录只允许使用代码内固定的 HTTPS 地址，播放器不会接受用户传入的任意 iframe 地址。 */
window.OpenNiceBrowserGames = Object.freeze([
  {
    slug: "smash-karts",
    rank: "07",
    title: "Smash Karts",
    initials: "SK",
    categories: ["pvp", "arcade"],
    search: "smash karts kart racing weapons multiplayer pvp arcade",
    tags: ["Kart battle", "Multiplayer", "PVP"],
    eyebrow: "Kart battle · Multiplayer",
    tagline: "Race, grab weapons and smash rival drivers in quick cartoon arenas.",
    description: "Drive through compact multiplayer arenas, collect surprise weapons and score knockouts before the match clock runs out.",
    cover: "assets/browser-games/smash-karts.jpg",
    source: "https://smashkarts.io/?gp",
    sourceLabel: "smashkarts.io",
    accent: "#ff5b8a",
    accentAlt: "#ffb52e"
  },
  {
    slug: "starblast",
    rank: "08",
    title: "Starblast.io",
    initials: "SB",
    categories: ["pvp", "strategy"],
    search: "starblast io space ship battle upgrade team strategy pvp",
    tags: ["Space", "Team battle", "Upgrades"],
    eyebrow: "Space combat · Team strategy",
    tagline: "Mine crystals, upgrade your ship and survive a glowing space war.",
    description: "Gather resources to evolve your spacecraft, cooperate with a team and choose when to fight in a large online arena.",
    cover: "assets/browser-games/starblast.jpg",
    source: "https://starblast.io/",
    sourceLabel: "starblast.io",
    accent: "#6e7bff",
    accentAlt: "#33e2ff"
  },
  {
    slug: "war-brokers",
    rank: "09",
    title: "War Brokers",
    initials: "WB",
    categories: ["pvp", "strategy"],
    search: "war brokers fps shooter vehicles tank helicopter multiplayer pvp strategy",
    tags: ["FPS", "Vehicles", "Multiplayer"],
    eyebrow: "Combined arms · Online FPS",
    tagline: "Fight on foot or take control of tanks, helicopters and other vehicles.",
    description: "Switch between infantry combat and powerful vehicles across blocky battlefields built for objective-based online matches.",
    cover: "assets/browser-games/war-brokers.jpg",
    source: "https://warbrokers.io/",
    sourceLabel: "warbrokers.io",
    accent: "#9bd56d",
    accentAlt: "#e9aa45"
  },
  {
    slug: "bonk",
    rank: "10",
    title: "Bonk.io",
    initials: "BK",
    categories: ["pvp", "arcade"],
    search: "bonk io physics multiplayer bump arena pvp arcade",
    tags: ["Physics", "Multiplayer", "Arena"],
    eyebrow: "Physics arena · Multiplayer",
    tagline: "Use momentum, timing and the map itself to knock rivals out.",
    description: "Control a small physics-driven ball, survive shifting arenas and bump opponents beyond the boundary in competitive rounds.",
    cover: "assets/browser-games/bonk.jpg",
    source: "https://bonk.io/",
    sourceLabel: "bonk.io",
    accent: "#72e4ff",
    accentAlt: "#6878ff"
  },
  {
    slug: "rocket-bot-royale",
    rank: "11",
    title: "Rocket Bot Royale",
    initials: "RB",
    categories: ["pvp", "arcade"],
    search: "rocket bot royale robot battle royale artillery multiplayer pvp arcade",
    tags: ["Battle royale", "Robots", "Action"],
    eyebrow: "Robot battle royale · Action",
    tagline: "Blast across a sinking island and be the last rocket bot standing.",
    description: "Use rocket jumps, terrain destruction and quick weapon choices to survive a compact multiplayer battle royale.",
    cover: "assets/browser-games/rocket-bot-royale.jpg",
    source: "https://rocketbotroyale.winterpixel.io/",
    sourceLabel: "winterpixel.io",
    accent: "#ff7b4f",
    accentAlt: "#f7df53"
  },
  {
    slug: "wormate",
    rank: "12",
    title: "Wormate.io",
    initials: "WM",
    categories: ["pvp", "arcade"],
    search: "wormate io snake sweets multiplayer pvp arcade casual",
    tags: ["Snake", "Multiplayer", "Casual"],
    eyebrow: "Snake arena · Casual PVP",
    tagline: "Eat sweets, grow longer and trap other worms without crashing.",
    description: "Navigate a colorful shared arena, collect treats to grow and use careful turns to outlast increasingly large opponents.",
    cover: "assets/browser-games/wormate.jpg",
    source: "https://wormate.io/",
    sourceLabel: "wormate.io",
    accent: "#c8ff55",
    accentAlt: "#ff5fa2"
  },
  {
    slug: "superhex",
    rank: "13",
    title: "Superhex.io",
    initials: "SH",
    categories: ["pvp", "strategy"],
    search: "superhex io territory capture multiplayer strategy pvp",
    tags: ["Territory", "Strategy", "Multiplayer"],
    eyebrow: "Territory control · Strategy",
    tagline: "Draw bold new borders while protecting every line back to your land.",
    description: "Expand your colored territory one risky loop at a time and cut through exposed rivals before they can return home.",
    cover: "assets/browser-games/superhex.jpg",
    source: "https://super-hex.io/",
    sourceLabel: "super-hex.io",
    accent: "#8b6dff",
    accentAlt: "#ff4fad"
  },
  {
    slug: "getaway-shootout",
    rank: "14",
    title: "Getaway Shootout",
    initials: "GS",
    categories: ["pvp", "arcade"],
    search: "getaway shootout two player physics racing shooting pvp arcade",
    tags: ["Two player", "Physics", "Action"],
    eyebrow: "Two-player chaos · Physics action",
    tagline: "Hop, tumble and fight through an absurd race to the getaway point.",
    description: "Master deliberately awkward movement, grab useful weapons and reach the extraction point before the other chaotic contestants.",
    cover: "assets/browser-games/getaway-shootout.jpg",
    source: "https://www.twoplayergames.org/embed/getaway-shootout",
    sourceLabel: "twoplayergames.org",
    accent: "#ffca44",
    accentAlt: "#ff574d"
  },
  {
    slug: "basketball-frvr",
    rank: "15",
    title: "Basketball FRVR",
    initials: "BF",
    categories: ["arcade"],
    search: "basketball frvr sports hoops shooting casual arcade",
    tags: ["Basketball", "Sports", "Casual"],
    eyebrow: "Basketball · Score chase",
    tagline: "Find a smooth shooting rhythm and keep the perfect streak alive.",
    description: "Aim simple swipe-and-release shots, adapt to the moving hoop and chase an ever-higher score in a clean casual challenge.",
    cover: "assets/browser-games/basketball-frvr.jpg",
    source: "https://basketball.frvr.com/",
    sourceLabel: "basketball.frvr.com",
    accent: "#ff8a3d",
    accentAlt: "#5ed8ff"
  },
  {
    slug: "2048",
    rank: "16",
    title: "2048",
    initials: "20",
    categories: ["strategy", "arcade"],
    search: "2048 number merge puzzle strategy casual arcade",
    tags: ["Puzzle", "Numbers", "Strategy"],
    eyebrow: "Number puzzle · Strategy",
    tagline: "Slide matching tiles together and plan enough space to reach 2048.",
    description: "Combine equal numbers, protect open cells and think several moves ahead in the enduring browser puzzle.",
    cover: "assets/browser-games/2048.jpg",
    source: "https://2048.io/",
    sourceLabel: "2048.io",
    accent: "#f2b760",
    accentAlt: "#ef7f65"
  },
  {
    slug: "bloxd",
    rank: "17",
    title: "Bloxd.io",
    initials: "BX",
    categories: ["pvp", "strategy", "arcade"],
    search: "bloxd io minecraft sandbox parkour building multiplayer pvp strategy arcade",
    tags: ["Sandbox", "Multiplayer", "Parkour"],
    eyebrow: "Block sandbox · Multiplayer",
    tagline: "Build, race and compete across a lively collection of block-world modes.",
    description: "Explore creative worlds, tackle parkour courses and jump into multiplayer challenges inspired by the freedom of block-building sandboxes.",
    cover: "assets/browser-games/bloxd.jpg",
    source: "https://bloxd.io/",
    sourceLabel: "bloxd.io",
    accent: "#61c7ff",
    accentAlt: "#80e45a"
  },
  {
    slug: "veck",
    rank: "18",
    title: "Veck.io",
    initials: "VK",
    categories: ["pvp", "arcade"],
    search: "veck io online shooter fps multiplayer arena pvp arcade",
    tags: ["FPS", "Multiplayer", "Arena"],
    eyebrow: "Arena FPS · Multiplayer",
    tagline: "Move fast, aim cleanly and outplay rivals in compact online firefights.",
    description: "Enter streamlined multiplayer arenas where responsive movement, weapon control and quick decisions determine every encounter.",
    cover: "assets/browser-games/veck.jpg?v=20260729b",
    source: "https://veck.io/",
    sourceLabel: "veck.io",
    accent: "#36dcff",
    accentAlt: "#9a63ff"
  },
  {
    slug: "frontwars",
    rank: "19",
    title: "FrontWars.io",
    initials: "FW",
    categories: ["pvp", "strategy"],
    search: "frontwars io war map territory economy multiplayer grand strategy pvp",
    tags: ["Grand strategy", "Territory", "Online"],
    eyebrow: "Grand strategy · Online war",
    tagline: "Expand your territory, manage resources and reshape a shared world map.",
    description: "Balance expansion, production and pressure from rival nations while directing a growing front across a persistent multiplayer map.",
    cover: "assets/browser-games/frontwars.jpg",
    source: "https://frontwars.io/",
    sourceLabel: "frontwars.io",
    accent: "#8ed66d",
    accentAlt: "#ef7d74"
  },
  {
    slug: "redcoats",
    rank: "20",
    title: "Redcoats.io",
    initials: "RC",
    categories: ["pvp", "strategy"],
    search: "redcoats io bluecoats musket fps cavalry cannon naval multiplayer pvp strategy",
    tags: ["Large-scale FPS", "Team battle", "Historical"],
    eyebrow: "Mass battle · Team FPS",
    tagline: "Choose a battlefield role and join enormous musket-era team conflicts.",
    description: "Fight as infantry, cavalry, artillery or naval crew while two armies compete for forts and territory across a large online battlefield.",
    cover: "assets/browser-games/redcoats.jpg",
    source: "https://redcoats.io/app/",
    sourceLabel: "redcoats.io",
    accent: "#ef4e4e",
    accentAlt: "#4e8eff"
  },
  {
    slug: "rocketgoal",
    rank: "21",
    title: "RocketGoal.io",
    initials: "RG",
    categories: ["pvp", "arcade"],
    search: "rocketgoal io rocket car soccer football sports multiplayer pvp arcade",
    tags: ["Car football", "Multiplayer", "Sports"],
    eyebrow: "Rocket cars · Online football",
    tagline: "Boost, jump and drive the ball home in fast online car-football matches.",
    description: "Control a rocket-powered car, read the bounce and coordinate aggressive attacks and last-second saves in compact multiplayer arenas.",
    cover: "assets/browser-games/rocketgoal.jpg",
    source: "https://rocketgoal.io/",
    sourceLabel: "rocketgoal.io",
    accent: "#ff8748",
    accentAlt: "#52d8ff"
  },
  {
    slug: "miniblox",
    rank: "22",
    title: "Miniblox.io",
    initials: "MB",
    categories: ["strategy", "arcade"],
    search: "miniblox io minecraft block sandbox building survival parkour strategy arcade",
    tags: ["Block building", "Sandbox", "Parkour"],
    eyebrow: "Block worlds · Creative sandbox",
    tagline: "Build freely, explore community worlds and master blocky obstacle courses.",
    description: "Switch between creative construction and skill-based minigames inside an accessible browser sandbox built around blocks and exploration.",
    cover: "assets/browser-games/miniblox.jpg?v=20260729b",
    source: "https://miniblox.io/",
    sourceLabel: "miniblox.io",
    accent: "#7be464",
    accentAlt: "#65bfff"
  },
  {
    slug: "venge",
    rank: "23",
    title: "Venge.io",
    initials: "VG",
    categories: ["pvp", "arcade"],
    search: "venge io fps shooter heroes abilities multiplayer pvp arcade",
    tags: ["FPS", "Heroes", "Multiplayer"],
    eyebrow: "Hero FPS · Online arena",
    tagline: "Pick a hero, capture objectives and combine gunplay with tactical abilities.",
    description: "Use distinct hero skills and responsive weapons to contest objectives across bright competitive maps designed for quick online matches.",
    cover: "assets/browser-games/venge.jpg",
    source: "https://venge.io/",
    sourceLabel: "venge.io",
    accent: "#ff535f",
    accentAlt: "#39c8ff"
  },
  {
    slug: "polytrack",
    rank: "24",
    title: "PolyTrack",
    initials: "PT",
    categories: ["arcade"],
    search: "polytrack low poly racing track builder time trial arcade official",
    tags: ["Racing", "Track builder", "Time trial"],
    eyebrow: "Low-poly racing · Official destination",
    tagline: "Chase precise time-trial lines and build imaginative low-poly tracks.",
    description: "Race against the clock on looping stunt courses, restart instantly and experiment with a flexible track editor on the authorized game page.",
    cover: "assets/browser-games/polytrack.jpg?v=20260729b",
    source: "https://www.crazygames.com/game/polytrack",
    sourceLabel: "crazygames.com",
    mode: "external",
    accent: "#ff8d44",
    accentAlt: "#66d7ff"
  },
  {
    slug: "paper-io-2",
    rank: "25",
    title: "Paper.io 2",
    initials: "P2",
    categories: ["pvp", "strategy", "arcade"],
    search: "paper io 2 territory capture casual multiplayer strategy arcade voodoo official",
    tags: ["Territory", "Casual", "Strategy"],
    eyebrow: "Territory capture · Official destination",
    tagline: "Draw new territory, close every loop and protect your growing color zone.",
    description: "Expand across a shared board by completing careful loops while watching exposed trails and opportunistic rivals on the official publisher page.",
    cover: "assets/browser-games/paper-io-2.jpg",
    source: "https://voodoo.io/paper2",
    sourceLabel: "voodoo.io",
    mode: "external",
    accent: "#b85bff",
    accentAlt: "#ffdc45"
  },
  {
    slug: "slice-master",
    rank: "26",
    title: "Slice Master",
    initials: "SM",
    categories: ["arcade"],
    search: "slice master knife cutting physics casual arcade playcalm poki official",
    tags: ["Slicing", "Physics", "Casual"],
    eyebrow: "Slicing challenge · Official destination",
    tagline: "Flip the blade, time each cut and carve through playful obstacle courses.",
    description: "Guide a tumbling knife through fruit, shapes and score gates in a timing-focused casual challenge hosted on the authorized publisher page.",
    cover: "assets/browser-games/slice-master.jpg?v=20260729b",
    source: "https://poki.com/en/g/slice-master",
    sourceLabel: "poki.com",
    mode: "external",
    accent: "#5ecbff",
    accentAlt: "#ffdf49"
  }
]);
